Document: kk
Title: Debian kk Manual
Author: <insert document author here>
Abstract: This manual describes what kk is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/kk/kk.sgml.gz

Format: postscript
Files: /usr/share/doc/kk/kk.ps.gz

Format: text
Files: /usr/share/doc/kk/kk.text.gz

Format: HTML
Index: /usr/share/doc/kk/html/index.html
Files: /usr/share/doc/kk/html/*.html
